baseURL = 'https://jysandy.github.io/'
languageCode = 'en-us'
title = 'Sandilya Jandhyala'
theme = 'typo'

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "Senior Engineer and Graphics Programmer"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
I'm Sandy, a graphics programmer and senior software engineer. 
I've worked with DirectX 12, implemented a range of rendering techniques and 
have developed a novel volumetric rendering technique.
"""

# Collection to display on home
homeCollectionTitle = 'Blog'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = false
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/jysandy/"


[[params.social]]
name = "github"
url = "https://github.com/jysandy"

# Main menu pages
# [[params.menu]]
# name = "home"
# url = "/"

# [[params.menu]]
# name = "about"
# url = "/about"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Needed for math rendering
[markup.goldmark]
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)']]
